global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fintech-api'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'

  - job_name: 'cadvisor'
    static_config:
      - targets: ['cadvisor:8080']
